version: "3.3"
services:
    mariadb:
        image: mariadb
        ports:
        -   3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: MyDBRoot123
            MYSQL_DATABASE: chat
            MYSQL_USER: node
            MYSQL_PASSWORD: toor
        networks:
            - instance

    auth-api:
        image: elliotalexander/clustered-api
        ports:
        -   3000:3000
        depends_on:
            -   mariadb
        networks:
        -   instance

    socket-api:
        image: elliotalexander/socket-api
        ports:
        -   4000:4000
        networks:
            - instance
        depends_on:
            -   auth-api

    nginx:
        image: elliotalexander/web-frontend
        ports:
            - 80:80
        volumes:
            - ./src/:/var/www/html
        depends_on:
            - auth-api
            - socket-api


    redis:
        image: redis
        ports:
            - 6379:6379
        networks:
            - instance
        depends_on:
            -   socket-api

networks:
    instance:
        driver: bridge